
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 15;
  public static final int GE = 18;
  public static final int LPAREN = 31;
  public static final int SEMI = 28;
  public static final int INT = 13;
  public static final int INTNUM = 39;
  public static final int MINUS = 24;
  public static final int RPAREN = 32;
  public static final int LT = 21;
  public static final int COMMA = 29;
  public static final int CLASS = 4;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int ASSIGN = 22;
  public static final int IF = 6;
  public static final int DOT = 30;
  public static final int LE = 19;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int FLOATNUM = 37;
  public static final int EQEQ = 16;
  public static final int MOD = 27;
  public static final int NEQ = 17;
  public static final int IDENT = 40;
  public static final int VOID = 5;
  public static final int ERROR = 42;
  public static final int LBRACK = 33;
  public static final int TIMES = 25;
  public static final int LBRACE = 35;
  public static final int ELSE = 7;
  public static final int READ = 10;
  public static final int RBRACK = 34;
  public static final int CHARCONST = 41;
  public static final int FINAL = 3;
  public static final int WHILE = 8;
  public static final int HEXNUM = 38;
  public static final int FLOAT = 14;
  public static final int RBRACE = 36;
  public static final int GT = 20;
  public static final int PRINT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "FINAL",
  "CLASS",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "READ",
  "PRINT",
  "NEW",
  "INT",
  "FLOAT",
  "CHAR",
  "EQEQ",
  "NEQ",
  "GE",
  "LE",
  "GT",
  "LT",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "SEMI",
  "COMMA",
  "DOT",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "FLOATNUM",
  "HEXNUM",
  "INTNUM",
  "IDENT",
  "CHARCONST",
  "ERROR"
  };
}

