
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 20;
  public static final int LBRACKET = 37;
  public static final int CHAR = 15;
  public static final int LPAREN = 35;
  public static final int NUM_INT = 17;
  public static final int NUM_HEX = 19;
  public static final int INT = 13;
  public static final int MINUS = 29;
  public static final int RPAREN = 36;
  public static final int SEMICOLON = 39;
  public static final int LT = 27;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int DIV = 31;
  public static final int GEQ = 23;
  public static final int PLUS = 28;
  public static final int IF = 6;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 38;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 32;
  public static final int NEQ = 22;
  public static final int IDENT = 16;
  public static final int VOID = 5;
  public static final int EQ = 25;
  public static final int TIMES = 30;
  public static final int LBRACE = 33;
  public static final int NUM_REAL = 18;
  public static final int ELSE = 7;
  public static final int READ = 10;
  public static final int FINAL = 3;
  public static final int WHILE = 8;
  public static final int FLOAT = 14;
  public static final int RBRACE = 34;
  public static final int LEQ = 24;
  public static final int GT = 26;
  public static final int PRINT = 11;
  public static final int EQ_EQ = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "FINAL",
  "CLASS",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "READ",
  "PRINT",
  "NEW",
  "INT",
  "FLOAT",
  "CHAR",
  "IDENT",
  "NUM_INT",
  "NUM_REAL",
  "NUM_HEX",
  "CHAR_CONST",
  "EQ_EQ",
  "NEQ",
  "GEQ",
  "LEQ",
  "EQ",
  "GT",
  "LT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "SEMICOLON",
  "COMMA",
  "DOT"
  };
}

